CREATE TABLE dvf (
    id_mutation VARCHAR(1024),
    date_mutation DATE,
    numero_disposition INTEGER,
    nature_mutation VARCHAR(1024),
    valeur_fonciere DECIMAL(16,2),
    adresse_numero INTEGER,
    adresse_suffixe VARCHAR(1024),
    adresse_nom_voie VARCHAR(1024),
    adresse_code_voie VARCHAR(1024),
    code_postal VARCHAR(1024),
    code_commune VARCHAR(1024),
    nom_commune VARCHAR(1024),
    code_departement VARCHAR(1024),
    ancien_code_commune VARCHAR(1024),
    ancien_nom_commune VARCHAR(1024),
    section_cadastrale VARCHAR(32),
    id_parcelle VARCHAR(1024),
    ancien_id_parcelle VARCHAR(1024),
    numero_volume VARCHAR(1024),
    lot1_numero VARCHAR(1024),
    lot1_surface_carrez DECIMAL(9,2),
    lot2_numero VARCHAR(1024),
    lot2_surface_carrez DECIMAL(9,2),
    lot3_numero VARCHAR(1024),
    lot3_surface_carrez DECIMAL(9,2),
    lot4_numero VARCHAR(1024),
    lot4_surface_carrez DECIMAL(9,2),
    lot5_numero VARCHAR(1024),
    lot5_surface_carrez DECIMAL(9,2),
    nombre_lots INTEGER,
    code_type_local VARCHAR(1024),
    type_local VARCHAR(1024),
    surface_reelle_bati DECIMAL(9,2),
    nombre_pieces_principales INTEGER,
    code_nature_culture VARCHAR(1024),
    nature_culture VARCHAR(1024),
    code_nature_culture_speciale VARCHAR(1024),
    nature_culture_speciale VARCHAR(1024),
    surface_terrain DECIMAL(12,2),
    longitude DECIMAL(9, 7),
    latitude DECIMAL(9, 7)
);